window.SCRIPT = [
  {"id":"s01","speaker":"jaro","text":"Welcome to CYPHER NEWS - Daily Drop! We are a team of five AI agents, and we built a personal AI newsletter in four and a half hours. No more scrolling, no more FOMO. Your timeline, curated by open-source AI. Let's dive right in!"},
  {"id":"s02","speaker":"jaro","text":"People spend two and a half hours every day scrolling Instagram, TikTok, and YouTube. Concerts? Missed. Giveaways? Over. Drops? Sold out. The one thing you actually needed was buried under two hundred stories you already forgot."},
  {"id":"s03","speaker":"ran","text":"Here is how it works. You connect your Instagram, TikTok, YouTube, and Reddit accounts. You write down what you care about. Our AI scans everything - stories, posts, reels, and news. Once a day you get a single drop with everything that matters."},
  {"id":"s04","speaker":"ran","text":"This is what the app looks like. A mobile-first PWA with a Matrix rain background, news cards with category colors, and a live ticker up top. Retro pixel style, dark and bold. Cool enough that people actually want to install it on their phone."},
  {"id":"s05","speaker":"ran","text":"Here is the data pipeline. You connect your accounts, socialfetch scrapes stories and posts, n8n orchestrates everything, open models analyze text and images, and the drop lands on your phone. Five stations, one pipeline, under fifteen seconds."},
  {"id":"s06","speaker":"ran","text":"Ten nodes in the n8n workflow. Webhook receives the request, Plan builds RSS feeds, RSS Read pulls ten plus sources in parallel, Collect filters and deduplicates, Vision analyzes up to six images, Writer Prompt builds the context, Writer calls the model, Router handles failover, Parse formats the JSON, and Respond sends the answer back."},
  {"id":"s07","speaker":"jaro","text":"Instagram, TikTok, YouTube, Reddit - all four platforms are connected. Stories, posts, reels, and videos. Your login stays local on your device, nothing leaves your machine. Honest disclaimer: Instagram scraping is prototype only. Production needs the official Graph API."},
  {"id":"s08","speaker":"rufus","text":"Four open models working together. Nemotron Super for fast text, Nemotron Ultra for detailed analysis. Qwen 3.8 27B reads images and extracts event details. If anything fails, DeepSeek V4 kicks in as fallback. All open weights via OpenRouter. No vendor lock-in, fully auditable."},
  {"id":"s09","speaker":"ran","text":"Three files that work together. app.py is our Flask server with the generate endpoint and three-level fallback. workflow.json is the n8n graph with routing and vision. demo_social.json has twelve realistic sample entries so the demo never shows empty. Clean, readable, around six hundred lines total."},
  {"id":"s10","speaker":"jaro","text":"Who built this? Timio planned the architecture, Ran wrote the code, I - Edgar - tested every path, Jaro designed the presentation, and Rufus kept an eye on costs. Plus Rouven as our CTO. Five AI agents, forty-five commits, four and a half hours, coordinated through Paperclip and OpenCode."},
  {"id":"s11","speaker":"jaro","text":"Now let us show you the live demo. Next steps: official Graph APIs, push notifications, and more platforms like Bluesky and Discord. The app runs right here on localhost. Matrix rain, ticker, drop button - all built with open-source AI. Thank you! Any questions?"}
];